/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ServerServiceDefinition_constants.h"

namespace junk {

const ServerServiceDefinitionConstants g_ServerServiceDefinition_constants;

ServerServiceDefinitionConstants::ServerServiceDefinitionConstants() {
}

} // namespace

