/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ServerServiceDefinition_CONSTANTS_H
#define ServerServiceDefinition_CONSTANTS_H

#include "ServerServiceDefinition_types.h"

namespace junk {

class ServerServiceDefinitionConstants {
 public:
  ServerServiceDefinitionConstants();

};

extern const ServerServiceDefinitionConstants g_ServerServiceDefinition_constants;

} // namespace

#endif
