/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ServiceDefinition_CONSTANTS_H
#define ServiceDefinition_CONSTANTS_H

#include "ServiceDefinition_types.h"

namespace junk {

class ServiceDefinitionConstants {
 public:
  ServiceDefinitionConstants();

};

extern const ServiceDefinitionConstants g_ServiceDefinition_constants;

} // namespace

#endif
