// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ServerService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::junk;

class ServerServiceHandler : virtual public ServerServiceIf {
 public:
  ServerServiceHandler() {
    // Your initialization goes here
  }

  void connected(const int32_t id) {
    // Your implementation goes here
    printf("connected\n");
  }

  void clientPositionUpdated(const int32_t id, const Vector2f& position) {
    // Your implementation goes here
    printf("clientPositionUpdated\n");
  }

  void clientDirectionUpdated(const int32_t id, const Vector2f& direction) {
    // Your implementation goes here
    printf("clientDirectionUpdated\n");
  }

  void fireUpdated() {
    // Your implementation goes here
    printf("fireUpdated\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ServerServiceHandler> handler(new ServerServiceHandler());
  shared_ptr<TProcessor> processor(new ServerServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

