/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ServiceDefinition_constants.h"

namespace junk {

const ServiceDefinitionConstants g_ServiceDefinition_constants;

ServiceDefinitionConstants::ServiceDefinitionConstants() {
}

} // namespace

