/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ClientServiceDefinition_constants.h"

namespace junk {

const ClientServiceDefinitionConstants g_ClientServiceDefinition_constants;

ClientServiceDefinitionConstants::ClientServiceDefinitionConstants() {
}

} // namespace

