/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ClientServiceDefinition_CONSTANTS_H
#define ClientServiceDefinition_CONSTANTS_H

#include "ClientServiceDefinition_types.h"

namespace junk {

class ClientServiceDefinitionConstants {
 public:
  ClientServiceDefinitionConstants();

};

extern const ClientServiceDefinitionConstants g_ClientServiceDefinition_constants;

} // namespace

#endif
